apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: helloworld
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: nimblepaultesthelloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: helloworld
